services:
  vault:
    build:
      context: ./vault
      dockerfile: Dockerfile
    ports:
      - "8200:8200"
    volumes:
      - ./vault/config:/vault/config:ro
      - ./vault/policies:/vault/policies:ro
      - vault-data:/vault/data
      - vault-logs:/vault/logs
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_API_ADDR=http://0.0.0.0:8200
    command: server -config=/vault/config/vault-config.json
    cap_add:
      - IPC_LOCK
    depends_on:
      - consul
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  consul:
    build:
      context: ./consul
      dockerfile: Dockerfile
    ports:
      - "8500:8500"
    volumes:
      - ./consul/config:/consul/config:ro
      - ./consul/policies:/consul/policies:ro
      - consul-data:/consul/data
    command: agent -server -ui -bind=0.0.0.0 -client=0.0.0.0 -bootstrap-expect=1 -config-file=/consul/config/consul-config.json
    environment:
      - CONSUL_HTTP_TOKEN=${CONSUL_HTTP_TOKEN:-root}
    healthcheck:
      test: ["CMD", "consul", "members"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  vault-data:
  vault-logs:
  consul-data:

networks:
  default:
    name: vault-consul-network
    driver: bridge
